version: 2.0
executorType: docker
containerInfo:
  - image: ruby:2.3.1
      - PGHOST=localhost
      - PGUSER=ubuntu
  - image: postgres:9.5.2
    env:
      - POSTGRES_USER=ubuntu
      - POSTGRES_DB=circle_test
stages:
  build:
    workDir: /home/ubuntu/wakes
    environment:
      RAILS_ENV: test
      RACK_ENV: test
      DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test
    steps:
      - type: checkout
      - type: cache-restore
        key: wakes-{{ .Branch }}-{{ checksum "wakes.gemspec" }}
      - type: shell
        name: "Dependencies"
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 
      - type: shell
        name: "RSpec"
        command: bundle exec rspec --format documentation --color --format RspecJunitFormatter --out /tmp/circle-junit.lR1NJfo/rspec/rspec.xml
      - type: shell
        command: bundle exec rubocop -d
      - type: cache-save
        key: wakes-{{ .Branch }}-{{ checksum "wakes.gemspec" }}
        paths:
          - /home/ubuntu/.bundle
          - /home/ubuntu/.go_workspace
          - /home/ubuntu/.m2
          - /home/ubuntu/.gradle
          - /home/ubuntu/.ivy2
          - /home/ubuntu/wakes/vendor/bundle
